{% set name = "koda" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/koda-{{ version }}.tar.gz
  sha256: 842774fadb96b1569217b8585db1291ed2261f8af243141a7cd67b59a8317505

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - koda
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/keithasaurus/koda
  summary: Type-safe functional tools for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
